version: "3.2"
services:
  database:
    container_name: database
    image: mysql5.7
    volumes:
      - ~/docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/var/log/mysql:/var/log/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    platform: linux/x86_64

  application:
    container_name: saveEnergy
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database